image: ubuntu:22.04

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "${SSH_PRIVATE_KEY}" > SSH_PRIVATE_KEY
    - chmod 600 SSH_PRIVATE_KEY
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - ls -lha && echo "Update code and restart Service"
    - ssh -i SSH_PRIVATE_KEY ${USERNAME}@${Server_IP} "pwd && cd /var/www/html/AI_Extert && sudo service nginx stop && sudo service gunicorn stop && sudo service daphne stop && git pull && sudo service gunicorn restart && sudo service daphne restart && sudo service nginx restart && echo 'nginx service' && systemctl is-active nginx && echo 'gunicorn service' && systemctl is-active gunicorn && echo 'daphne service' && systemctl is-active daphne && exit"

  only:
    - master