# Generated by Django 4.2.9 on 2024-02-08 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievemate_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiCoach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coach_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "coach_expertise",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "coach_experience",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("coach_about", models.TextField(blank=True, null=True)),
                (
                    "coach_degree",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "coach_profile_image",
                    models.FileField(
                        blank=True, null=True, upload_to="coach_profile_pic/"
                    ),
                ),
                ("coaching_types", models.TextField(blank=True, null=True)),
                ("target_audience", models.TextField(blank=True, null=True)),
                ("specialities", models.TextField(blank=True, null=True)),
                ("languages", models.TextField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("is_testdata", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ai_coach",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_text", models.TextField(blank=True, null=True)),
                (
                    "user_type",
                    models.CharField(
                        blank=True,
                        choices=[("coach", "coach"), ("user", "user")],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("is_testdata", models.BooleanField(default=True)),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="achievemate_app.aicoach",
                    ),
                ),
            ],
            options={
                "db_table": "chat",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FindCoachQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(blank=True, null=True)),
                (
                    "question_type",
                    models.CharField(
                        blank=True,
                        choices=[("mcq", "MCQ"), ("textual", "Textual")],
                        max_length=7,
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("is_testdata", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "find_coach_questions",
                "managed": True,
            },
        ),
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[("coach", "coach"), ("user", "user")],
                default="user",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=255, null=True)),
                ("lastname", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "profilepic",
                    models.FileField(
                        blank=True, null=True, upload_to="user_profile_pic/"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("is_testdata", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profile",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("is_testdata", models.BooleanField(default=True)),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="achievemate_app.findcoachquestions",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_answer",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "task_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("started", "started"),
                            ("in_progress", "in_progress"),
                            ("need_attention", "need_attention"),
                            ("completed", "completed"),
                        ],
                        max_length=14,
                        null=True,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("is_testdata", models.BooleanField(default=True)),
                (
                    "chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="achievemate_app.chat",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="achievemate_app.aicoach",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
