# Generated by Django 4.1 on 2024-02-09 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "achievemate_app",
            "0002_aicoach_chat_findcoachquestions_alter_users_role_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="is_testdata",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(-128),
                    django.core.validators.MaxValueValidator(127),
                ],
            ),
        ),
    ]
