# Generated by Django 4.1 on 2024-02-12 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievemate_app", "0003_alter_tasks_is_testdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "package_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        blank=True,
                        choices=[("yearly", "yearly"), ("monthly ", "monthly")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_delete", models.IntegerField(blank=True, null=True)),
                ("is_testdata", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "subscription",
                "managed": True,
            },
        ),
        migrations.AlterField(
            model_name="aicoach",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_delete", models.IntegerField(blank=True, null=True)),
                ("is_testdata", models.IntegerField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievemate_app.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_features",
                "managed": True,
            },
        ),
        migrations.AlterField(
            model_name="users",
            name="subscription_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="achievemate_app.subscription",
            ),
        ),
    ]
