# Generated by Django 4.1 on 2024-02-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievemate_app", "0004_subscription_alter_aicoach_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aicoach",
            name="is_testdata",
            field=models.SmallIntegerField(
                blank=True,
                choices=[("0", "yes"), ("1", "no"), ("2", "default")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="is_testdata",
            field=models.SmallIntegerField(
                blank=True,
                choices=[("0", "yes"), ("1", "no"), ("2", "default")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="findcoachquestions",
            name="is_testdata",
            field=models.SmallIntegerField(
                blank=True,
                choices=[("0", "yes"), ("1", "no"), ("2", "default")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_testdata",
            field=models.SmallIntegerField(
                blank=True,
                choices=[("0", "yes"), ("1", "no"), ("2", "default")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionfeatures",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subscriptionfeatures",
            name="is_testdata",
            field=models.SmallIntegerField(
                blank=True,
                choices=[("0", "yes"), ("1", "no"), ("2", "default")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="is_testdata",
            field=models.SmallIntegerField(
                blank=True,
                choices=[("0", "yes"), ("1", "no"), ("2", "default")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="is_testdata",
            field=models.SmallIntegerField(
                blank=True,
                choices=[("0", "yes"), ("1", "no"), ("2", "default")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_testdata",
            field=models.SmallIntegerField(
                blank=True,
                choices=[("0", "yes"), ("1", "no"), ("2", "default")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_testdata",
            field=models.SmallIntegerField(
                blank=True,
                choices=[("0", "yes"), ("1", "no"), ("2", "default")],
                default=1,
                null=True,
            ),
        ),
    ]
