# Generated by Django 4.1 on 2024-02-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "achievemate_app",
            "0006_alter_aicoach_is_testdata_alter_chat_is_testdata_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="aicoach",
            old_name="is_delete",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="chat",
            old_name="is_delete",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="findcoachquestions",
            old_name="is_delete",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="is_delete",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="subscriptionfeatures",
            old_name="is_delete",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="tasks",
            old_name="is_delete",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="useranswer",
            old_name="is_delete",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="is_delete",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="is_delete",
            new_name="is_deleted",
        ),
    ]
