# Generated by Django 4.1 on 2024-02-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievemate_app", "0007_rename_is_delete_aicoach_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aicoach",
            name="is_testdata",
            field=models.CharField(
                blank=True,
                choices=[("0", "no"), ("1", "yes"), ("2", "default")],
                default="1",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="is_testdata",
            field=models.CharField(
                blank=True,
                choices=[("0", "no"), ("1", "yes"), ("2", "default")],
                default="1",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="findcoachquestions",
            name="is_testdata",
            field=models.CharField(
                blank=True,
                choices=[("0", "no"), ("1", "yes"), ("2", "default")],
                default="1",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_testdata",
            field=models.CharField(
                blank=True,
                choices=[("0", "no"), ("1", "yes"), ("2", "default")],
                default="1",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionfeatures",
            name="is_testdata",
            field=models.CharField(
                blank=True,
                choices=[("0", "no"), ("1", "yes"), ("2", "default")],
                default="1",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="is_testdata",
            field=models.CharField(
                blank=True,
                choices=[("0", "no"), ("1", "yes"), ("2", "default")],
                default="1",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="is_testdata",
            field=models.CharField(
                blank=True,
                choices=[("0", "no"), ("1", "yes"), ("2", "default")],
                default="1",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_testdata",
            field=models.CharField(
                blank=True,
                choices=[("0", "no"), ("1", "yes"), ("2", "default")],
                default="1",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_testdata",
            field=models.CharField(
                blank=True,
                choices=[("0", "no"), ("1", "yes"), ("2", "default")],
                default="1",
                max_length=1,
                null=True,
            ),
        ),
    ]
