# Generated by Django 4.1 on 2024-02-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "achievemate_app",
            "0008_alter_aicoach_is_testdata_alter_chat_is_testdata_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="subscription_status",
            field=models.CharField(
                choices=[("active", "active"), ("inactive", "inactive")],
                default="inactive",
                max_length=255,
            ),
        ),
    ]
