# Generated by Django 4.1 on 2024-02-15 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievemate_app", "0009_alter_users_subscription_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "is_testdata",
                    models.CharField(
                        blank=True,
                        choices=[("0", "no"), ("1", "yes"), ("2", "default")],
                        default="1",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "package_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "subscription_package",
                "managed": True,
            },
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="package_cost",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="package_name",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="package_type",
        ),
        migrations.AddField(
            model_name="subscription",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="achievemate_app.subscriptionpackage",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionfeatures",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="achievemate_app.subscriptionpackage",
            ),
        ),
    ]
