# Generated by Django 4.1 on 2024-02-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievemate_app", "0010_subscriptionpackage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionfeatures",
            old_name="subscription",
            new_name="subscription_package",
        ),
    ]
