# Generated by Django 4.1 on 2024-03-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "achievemate_app",
            "0011_rename_subscription_subscriptionfeatures_subscription_package",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="task_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("started", "started"),
                    ("in_progress", "in_progress"),
                    ("need_attention", "need_attention"),
                    ("completed", "completed"),
                ],
                default="started",
                max_length=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="task_title",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profilepic",
            field=models.FileField(
                blank=True,
                default="user_profile_pic/anonymous.png",
                null=True,
                upload_to="user_profile_pic/",
            ),
        ),
    ]
