# Generated by Django 4.1 on 2024-03-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "achievemate_app",
            "0012_alter_tasks_task_status_alter_tasks_task_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="task_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Remaining", "Remaining"),
                    ("In Progress", "In Progress"),
                    ("Done", "Done"),
                    ("Delayed", "Delayed"),
                ],
                default="Remaining",
                max_length=14,
                null=True,
            ),
        ),
    ]
