# Generated by Django 4.1 on 2024-03-22 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievemate_app", "0013_alter_tasks_task_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity_Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "is_testdata",
                    models.CharField(
                        blank=True,
                        choices=[("0", "no"), ("1", "yes"), ("2", "default")],
                        default="1",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("task_cretated", "Task Created"),
                            ("task_in_progress", "Task In Progress"),
                            ("task_completed", "Task Completed"),
                            ("comment_added", "Comment Added"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "notification_comment",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="achievemate_app.aicoach",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
