# Generated by Django 4.1 on 2024-03-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievemate_app", "0014_activity_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity_log",
            name="activity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("task_created", "Task Created"),
                    ("task_in_progress", "Task In Progress"),
                    ("task_completed", "Task Completed"),
                    ("comment_added", "Comment Added"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
