# Generated by Django 4.1 on 2024-03-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievemate_app", "0015_alter_activity_log_activity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity_log",
            name="tasks",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="achievemate_app.tasks",
            ),
        ),
        migrations.AlterField(
            model_name="activity_log",
            name="activity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("task_created", "Task Created"),
                    ("task_in_progress", "Task In Progress"),
                    ("task_completed", "Task Completed"),
                    ("task_remaining", "Task Remaining"),
                    ("task_delayed", "Task Delayed"),
                    ("comment_added", "Comment Added"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
