# Generated by Django 4.1 on 2024-03-29 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievemate_app", "0016_activity_log_tasks_alter_activity_log_activity_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task_Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "is_testdata",
                    models.CharField(
                        blank=True,
                        choices=[("0", "no"), ("1", "yes"), ("2", "default")],
                        default="1",
                        max_length=1,
                        null=True,
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "tasks",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="achievemate_app.tasks",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "task_comments",
                "managed": True,
            },
        ),
    ]
