# Generated by Django 4.1 on 2024-05-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievemate_app", "0017_task_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
