# Generated by Django 4.1 on 2024-06-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievemate_app", "0020_userstripe"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstripe",
            name="is_active",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userstripe",
            name="plan",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
