# Generated by Django 4.1 on 2024-06-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievemate_app", "0021_userstripe_is_active_userstripe_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstripe",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="achievemate_app.subscription",
            ),
        ),
    ]
